// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4g6ZYnnbBugi3CZLLVqqZbbGAhzepk7k',
    appId: '1:762247319352:web:02693d96cb71e254ab7bcd',
    messagingSenderId: '762247319352',
    projectId: 'employee-364ba',
    authDomain: 'employee-364ba.firebaseapp.com',
    storageBucket: 'employee-364ba.appspot.com',
    measurementId: 'G-650LDQ2Y7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiSIz3CZAfqq7kYHs1-4ZkO5WNbjJXRAE',
    appId: '1:762247319352:android:46156332210a0312ab7bcd',
    messagingSenderId: '762247319352',
    projectId: 'employee-364ba',
    storageBucket: 'employee-364ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKaqGv2PA_kySosHRw35ObpNy2MZNg7vo',
    appId: '1:762247319352:ios:0a600fd788b1a52bab7bcd',
    messagingSenderId: '762247319352',
    projectId: 'employee-364ba',
    storageBucket: 'employee-364ba.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKaqGv2PA_kySosHRw35ObpNy2MZNg7vo',
    appId: '1:762247319352:ios:0a600fd788b1a52bab7bcd',
    messagingSenderId: '762247319352',
    projectId: 'employee-364ba',
    storageBucket: 'employee-364ba.appspot.com',
    iosBundleId: 'com.example.employeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4g6ZYnnbBugi3CZLLVqqZbbGAhzepk7k',
    appId: '1:762247319352:web:17c4f1414fdc3189ab7bcd',
    messagingSenderId: '762247319352',
    projectId: 'employee-364ba',
    authDomain: 'employee-364ba.firebaseapp.com',
    storageBucket: 'employee-364ba.appspot.com',
    measurementId: 'G-F0N5X13WB2',
  );

}